kind: Service
apiVersion: v1
metadata:
  name: cicdgcp-reactjs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 443
      protocol: TCP
      nodePort: 32500
  selector:
    role: reactjs
    app: reactjs