apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-prod
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-frontend-prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react-frontend-prod
    spec:
      containers:
        - image: gcr.io/project-id/react-frontend-prod
          imagePullPolicy: IfNotPresent
          name: react-frontend-prod
          ports:
            - containerPort: 4001
              protocol: TCP
---
  apiVersion: v1
  kind: Service
  metadata:
    name: react-frontend-prod
    namespace: default
  spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 4001
    selector:
      app: react-frontend-prod
    sessionAffinity: None
    type: LoadBalancer