kind: Deployment
apiVersion: apps/v1
metadata:
  name: cicdgcp-reactjs-production
spec:
  replicas: 2
  selector:
      matchLabels:
          app: cicdgcp
          role: reactjs
          env: production
  template:
    metadata:
      name: reactjs
      labels:
        app: cicdgcp
        role: reactjs
        env: production
    spec:
      containers:
      - name: reactjs
        image: gcr.io/cloud-solutions-images/cicdgcp:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["sh", "-c", "app -port=80"]
        ports:
        - name: reactjs
          containerPort: 443

